name: this genuine life
favicon: null
layout_spectrum: 0.99729
typography_spectrum: 0.9991
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c322b'
    - '#49719b'
    - '#a6b7c6'
    - '#f7f1e6'
    - '#b3834f'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
