name: this genuine life
favicon: null
layout_spectrum: 0.34928
typography_spectrum: 0.84025
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a9cdf2'
    - '#171e24'
    - '#4d6c9d'
    - '#fefdfd'
    - '#4c4337'
  brandStrength: 0.9375
  lightness: 0.5923379911109805
  saturation: 0.9394962161313742
  rhythmicContrast: 0.3497538845986128
purpose: []
