name: this genuine life
favicon: null
layout_spectrum: 0.99729
typography_spectrum: 0.9991
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5288b9'
    - '#ffffff'
    - '#0c1a3f'
    - '#cc849f'
    - '#d5cdfe'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
